# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b43b69107824ebea5cb08d805adc9de6a2d5e632b3e32fc2b2e70b48c029e1299b38ce1b888e265931d08910af2bc4a18189e48c1a90966f53721c8e4ab9ea0

test:
  secret_key_base: df79f161d81e054e37e4c4a4d38fec67960ec0599093a227e085059df883a97e9f2e3de0f2732b05737995205e2834dd747e74a1590e172b9e33f3aa0df0cec7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
